Repository ArvinYang1925/kaiso-meow-frontend, pull requests merged in 2025-06, with the labels that each got.

#66 feat: 🎸 結帳完成頁面增加按鈕
  src/lib/priceHelper.ts
  src/pages/student/checkout-page/CheckoutPage.tsx
  src/pages/student/order-list-page/OrderListPage.tsx
  src/pages/student/order-page/constants/initialData.ts
  src/pages/student/order-page/service/type.ts
Labels: 優先權-高

#72 refactor: 💡 調整結帳後"繼續購買"導到首頁後滾動至"強打課程"區塊
  src/pages/student/checkout-page/CheckoutPage.tsx
  src/pages/student/home-page/HomePage.tsx
Labels: 優先權-中

#124 fix: 🐛 課程列表不需使用準備中遮罩
  src/pages/student/course-list-page/CourseListPage.tsx
Labels: 優先權-高, bug

#127 fix: 🐛 update avator when chanege user name
  src/pages/student/profile-page/profileStore.ts
  src/stores/authStore.ts
Labels: 優先權-高, bug, 需要兩人 Review
